-- Development reset: keep users, pets, OAuth data, and settings.
-- Child rows must be removed before their parent ALERTS rows.

DELETE FROM EMERGENCY_CLIPS WHERE CLIP_ID IS NOT NULL;
DELETE FROM ALERTS WHERE ALERT_ID IS NOT NULL;
DELETE FROM CLIPS WHERE CLIP_ID IS NOT NULL;
DELETE FROM DETECTION_LOGS WHERE LOG_ID IS NOT NULL;
DELETE FROM DAILY_ACTIVITY_SUMMARIES WHERE SUMMARY_ID IS NOT NULL;
DELETE FROM PET_HEALTH_REPORTS WHERE REPORT_ID IS NOT NULL;
DELETE FROM FEED_LOGS WHERE FEED_ID IS NOT NULL;
DELETE FROM WATER_LOGS WHERE WATER_LOG_ID IS NOT NULL;

COMMIT;
