-- Run once after clear_operational_logs.sql.
-- DAILY_ACTIVITY_SUMMARIES changes from one row per day to four time-slot rows per day.

ALTER TABLE DAILY_ACTIVITY_SUMMARIES
    ADD TIME_SLOT VARCHAR2(20) DEFAULT 'MORNING' NOT NULL;

ALTER TABLE DAILY_ACTIVITY_SUMMARIES
    DROP CONSTRAINT UQ_DAILY_ACTIVITY_PET_DATE;

ALTER TABLE DAILY_ACTIVITY_SUMMARIES
    ADD CONSTRAINT UQ_DAILY_ACTIVITY_PET_DATE_SLOT
    UNIQUE (PET_ID, SUMMARY_DATE, TIME_SLOT);

COMMIT;
